/* base human type with Scottish clans */

var scot = new Homo();

addRace("scot", "Human: Scottish", scot);

scot.clanList = [
	'Agnew',
	'Anstruther',
	'Arbuthnott',
	'Arthur',
	'Bannerman',
	'Barclay',
	'Borthwick',
	'Boyd',
	'Boyle',
	'Brodie',
	'Broun',
	'Bruce',
	'Buchan',
	'Burnett',
	'Cameron',
	'Campbell',
	'Carmichael',
	'Carnegie',
	'Cathcart',
	'Charteris',
	'Chattan',
	'Chisholm',
	'Cochrane',
	'Colquhoun',
	'Colville',
	'Cranstoun',
	'Crichton',
	'Cumming (Comyn)',
	'Darroch',
	'Davidson',
	'Dewar',
	'Drummond',
	'Dunbar',
	'Dundas',
	'Durie',
	'Elliot',
	'Elphinstone',
	'Erskine',
	'Farquharson',
	'Fergusson',
	'Forbes',
	'Forsyth',
	'Fraser',
	'Fraser of Lovat',
	'Gordon',
	'Graham',
	'Grant',
	'Gregor',
	'Grierson',
	'Guthrie',
	'Haig',
	'Haldane',
	'Hamilton',
	'Hannay',
	'Hay',
	'Henderson',
	'Home',
	'Hope',
	'Hunter',
	'Irvine',
	'Jardine',
	'Johnstone',
	'Keith',
	'Kennedy',
	'Kerr',
	'Kincaid',
	'Lamont',
	'Leask',
	'Lennox',
	'Leslie',
	'Lindsay',
	'Lockhart',
	'Lumsden',
	'Lyon',
	'MacAlister',
	'MacBean',
	'MacDonald',
	'Macdonald of Clanranald',
	'MacDonald of Keppoch',
	'Macdonald of Sleat',
	'MacDonell of Glengarry',
	'MacDougall',
	'Macdowall',
	'MacIntyre',
	'Mackay',
	'Mackenzie',
	'Mackinnon',
	'Mackintosh',
	'Maclachlan',
	'Maclaine of Lochbuie',
	'MacLaren',
	'MacLea (Livingstone)',
	'Maclean',
	'MacLennan',
	'MacLeod',
	'MacLeod of Lewis',
	'MacMillan',
	'Macnab',
	'Macnaghten',
	'MacNeacail',
	'MacNeil',
	'Macpherson',
	'MacTavish',
	'MacThomas',
	'Maitland',
	'Makgill',
	'Malcolm (MacCallum)',
	'Mar',
	'Marjoribanks',
	'Matheson',
	'Menzies',
	'Moffat',
	'Moncreiffe',
	'Montgomery',
	'Morrison',
	'Munro',
	'Murray',
	'Napier',
	'Nesbitt',
	'Nicolson',
	'Ogilvy',
	'Oliphant',
	'Primrose',
	'Ramsay',
	'Rattray',
	'Riddell',
	'Robertson',
	'Rollo',
	'Rose',
	'Ross',
	'Ruthven',
	'Sandilands',
	'Scott',
	'Scrymgeour',
	'Sempill',
	'Shaw',
	'Sinclair',
	'Skene',
	'Spens',
	'Stirling',
	'Strange',
	'Stuart of Bute',
	'Sutherland',
	'Swinton',
	'Trotter',
	'Urquhart',
	'Wallace',
	'Wedderburn',
	'Wemyss',
	'Wood'
]

	// clan generation
scot.generateClan = function() { // random clan
	return rollD(homo.clanList.length) - 1;
};

scot.getClan = function(person) {
	//get clan name from clan ID
	return scot.clanList[person.clan];
};

scot.initializeClans = function() {
	var appendage = "";
	for  (var i = 0; i < scot.clanList.length; i++) {
		appendage = "<option value='" + i + "'>" + scot.clanList[i] + "</option>";
		$("select#clan1SELECT").append(appendage);
		$("select#clan2SELECT").append(appendage);
	}
};
